/**
 * This class is generated by jOOQ
 */
package com.example.dao.entity.tables;


import com.example.dao.entity.Keys;
import com.example.dao.entity.Public;
import com.example.dao.entity.tables.records.CarAdvertsRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CarAdverts extends TableImpl<CarAdvertsRecord> {

	private static final long serialVersionUID = 1733045613;

	/**
	 * The reference instance of <code>PUBLIC.CAR-ADVERTS</code>
	 */
	public static final CarAdverts CAR_ADVERTS = new CarAdverts();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<CarAdvertsRecord> getRecordType() {
		return CarAdvertsRecord.class;
	}

	/**
	 * The column <code>PUBLIC.CAR-ADVERTS.GUID</code>.
	 */
	public final TableField<CarAdvertsRecord, String> GUID = createField("GUID", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.CAR-ADVERTS.TITLE</code>.
	 */
	public final TableField<CarAdvertsRecord, String> TITLE = createField("TITLE", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.CAR-ADVERTS.FUEL</code>.
	 */
	public final TableField<CarAdvertsRecord, String> FUEL = createField("FUEL", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.CAR-ADVERTS.PRICE</code>.
	 */
	public final TableField<CarAdvertsRecord, Integer> PRICE = createField("PRICE", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.CAR-ADVERTS.IS_NEW</code>.
	 */
	public final TableField<CarAdvertsRecord, Boolean> IS_NEW = createField("IS_NEW", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.CAR-ADVERTS.MILEAGE</code>.
	 */
	public final TableField<CarAdvertsRecord, Integer> MILEAGE = createField("MILEAGE", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>PUBLIC.CAR-ADVERTS.FIRST_REGISTRATION</code>.
	 */
	public final TableField<CarAdvertsRecord, Timestamp> FIRST_REGISTRATION = createField("FIRST_REGISTRATION", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * Create a <code>PUBLIC.CAR-ADVERTS</code> table reference
	 */
	public CarAdverts() {
		this("CAR-ADVERTS", null);
	}

	/**
	 * Create an aliased <code>PUBLIC.CAR-ADVERTS</code> table reference
	 */
	public CarAdverts(String alias) {
		this(alias, CAR_ADVERTS);
	}

	private CarAdverts(String alias, Table<CarAdvertsRecord> aliased) {
		this(alias, aliased, null);
	}

	private CarAdverts(String alias, Table<CarAdvertsRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<CarAdvertsRecord> getPrimaryKey() {
		return Keys.CAR_ADVERTS_PK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<CarAdvertsRecord>> getKeys() {
		return Arrays.<UniqueKey<CarAdvertsRecord>>asList(Keys.CAR_ADVERTS_PK);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CarAdverts as(String alias) {
		return new CarAdverts(alias, this);
	}

	/**
	 * Rename this table
	 */
	public CarAdverts rename(String name) {
		return new CarAdverts(name, null);
	}
}
