/**
 * This class is generated by jOOQ
 */
package com.example.dao.entity.tables.records;


import com.example.dao.entity.tables.CarAdverts;

import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "CAR-ADVERTS", schema = "PUBLIC")
public class CarAdvertsRecord extends UpdatableRecordImpl<CarAdvertsRecord> implements Record7<String, String, String, Integer, Boolean, Integer, Timestamp> {

	private static final long serialVersionUID = -1046316701;

	/**
	 * Setter for <code>PUBLIC.CAR-ADVERTS.GUID</code>.
	 */
	public void setGuid(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>PUBLIC.CAR-ADVERTS.GUID</code>.
	 */
	@Id
	@Column(name = "GUID", unique = true, nullable = false, length = 100)
	public String getGuid() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>PUBLIC.CAR-ADVERTS.TITLE</code>.
	 */
	public void setTitle(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>PUBLIC.CAR-ADVERTS.TITLE</code>.
	 */
	@Column(name = "TITLE", nullable = false, length = 100)
	public String getTitle() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>PUBLIC.CAR-ADVERTS.FUEL</code>.
	 */
	public void setFuel(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>PUBLIC.CAR-ADVERTS.FUEL</code>.
	 */
	@Column(name = "FUEL", nullable = false, length = 100)
	public String getFuel() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>PUBLIC.CAR-ADVERTS.PRICE</code>.
	 */
	public void setPrice(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>PUBLIC.CAR-ADVERTS.PRICE</code>.
	 */
	@Column(name = "PRICE", nullable = false, precision = 10)
	public Integer getPrice() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>PUBLIC.CAR-ADVERTS.IS_NEW</code>.
	 */
	public void setIsNew(Boolean value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>PUBLIC.CAR-ADVERTS.IS_NEW</code>.
	 */
	@Column(name = "IS_NEW", nullable = false, precision = 1)
	public Boolean getIsNew() {
		return (Boolean) getValue(4);
	}

	/**
	 * Setter for <code>PUBLIC.CAR-ADVERTS.MILEAGE</code>.
	 */
	public void setMileage(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>PUBLIC.CAR-ADVERTS.MILEAGE</code>.
	 */
	@Column(name = "MILEAGE", precision = 10)
	public Integer getMileage() {
		return (Integer) getValue(5);
	}

	/**
	 * Setter for <code>PUBLIC.CAR-ADVERTS.FIRST_REGISTRATION</code>.
	 */
	public void setFirstRegistration(Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>PUBLIC.CAR-ADVERTS.FIRST_REGISTRATION</code>.
	 */
	@Column(name = "FIRST_REGISTRATION", precision = 23, scale = 10)
	public Timestamp getFirstRegistration() {
		return (Timestamp) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<String, String, String, Integer, Boolean, Integer, Timestamp> fieldsRow() {
		return (Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<String, String, String, Integer, Boolean, Integer, Timestamp> valuesRow() {
		return (Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return CarAdverts.CAR_ADVERTS.GUID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return CarAdverts.CAR_ADVERTS.TITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return CarAdverts.CAR_ADVERTS.FUEL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return CarAdverts.CAR_ADVERTS.PRICE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field5() {
		return CarAdverts.CAR_ADVERTS.IS_NEW;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return CarAdverts.CAR_ADVERTS.MILEAGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field7() {
		return CarAdverts.CAR_ADVERTS.FIRST_REGISTRATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getGuid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getFuel();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getPrice();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value5() {
		return getIsNew();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getMileage();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value7() {
		return getFirstRegistration();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CarAdvertsRecord value1(String value) {
		setGuid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CarAdvertsRecord value2(String value) {
		setTitle(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CarAdvertsRecord value3(String value) {
		setFuel(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CarAdvertsRecord value4(Integer value) {
		setPrice(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CarAdvertsRecord value5(Boolean value) {
		setIsNew(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CarAdvertsRecord value6(Integer value) {
		setMileage(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CarAdvertsRecord value7(Timestamp value) {
		setFirstRegistration(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CarAdvertsRecord values(String value1, String value2, String value3, Integer value4, Boolean value5, Integer value6, Timestamp value7) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CarAdvertsRecord
	 */
	public CarAdvertsRecord() {
		super(CarAdverts.CAR_ADVERTS);
	}

	/**
	 * Create a detached, initialised CarAdvertsRecord
	 */
	public CarAdvertsRecord(String guid, String title, String fuel, Integer price, Boolean isNew, Integer mileage, Timestamp firstRegistration) {
		super(CarAdverts.CAR_ADVERTS);

		setValue(0, guid);
		setValue(1, title);
		setValue(2, fuel);
		setValue(3, price);
		setValue(4, isNew);
		setValue(5, mileage);
		setValue(6, firstRegistration);
	}
}
