/**
 * This class is generated by jOOQ
 */
package com.example.dao.entity;


import com.example.dao.entity.tables.CarAdverts;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table PUBLIC.CAR-ADVERTS
	 */
	public static final CarAdverts CAR_ADVERTS = com.example.dao.entity.tables.CarAdverts.CAR_ADVERTS;
}
